version: "3.9"

services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tododb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5